### PR TITLE
added default cmd line params values and 'make install'

### PR DESCRIPTION
**Pull request by piontec**

### CODE REVIEW

**Comment by DimmKirr** [comment]
@piontec I assume this is tested?
@alonewolfx2 can we please merge this, otherwise upgrading will break backwards compatibility

**Comment by alonewolfx2** [comment]
@kireevco Unfortunately i cant merge this. because some part of this pr not working correctly on windows.but i can add some parameter for backwards compatibility and nodemcu today.

**Comment by DimmKirr** [comment]
@alonewolfx2 that would be helpful. I set up a build pipeline and I'm ready to rebuild 1.0.4 again, just ping me.

**Comment by piontec** [comment]
There is still one decision to make: which files from web/dev/ to process. Sming's web server is smart - if it finds file ending with .gz, it sends it instead of requested file. This allows for gzipping of all files and minification of .css and .js before that.
If not all files should be gzipped, then Makefile needs to copy all remeaning files from web/dev/ to files/.
ABout integrating this makefile to core: that's what I intended, just I'm no Makefile wizzard, so I prefered to write it in a separate file - to not break anything.
About testing: I'm using this workflow since yeasterday with my project, inside kireevco's docker container - and yeah, at last it works as it should :) You have just one copy of source web files, you run make, make web, make flash - and everything is on the chip :)

So, someone smart: please make Makefile adjustments as needed before releasing.

**Comment by DimmKirr** [comment]
@piontec why not just add all files form the directory we're pointing to? Also, makefile will change, we just need to push this backwards-compatibility update.
@alonewolfx2 any progress on adding defaults? We really need this, I need to push choco update for spiffy.

**Comment by piontec** [comment]
@kireevco that's what I was talking about: all files from teh source dir to destination must be copied, but either with or without gzip compression. Thanks to support in Sming's web server, compression should 'just work', as long as browser will recognize 'content-encoding' header.
And what do you mean by 'makefile will change'?

**Comment by flexiti** [comment]
@alonewolfx2 
Now I can  again test spiffy, on what sources I have to work?

**Comment by alonewolfx2** [comment]
@flexiti master branch. if you use sming develop branch, you must to use spiffy develop branch

**Comment by flexiti** [comment]
Thanks,  I have seen that there are not marged patch #307

**Comment by flexiti** [comment]
@alonewolfx2 
I see you changed your errno as I suggested, but despite the good compilation have effect as in the picture. (the same  I had before)
This file spiffy.exe that you shared it with me - it works, compiled by me not.
(the entire compilation is ok, do not show errors)
Interestingly, Your file is about 800 kb, while my 130 kb. ??????????????
Do you compile it all the debug options enabled? Only that would explain why you have such a large output spiffy.exe file.
Can you compile with debugging options turned off and check ?
@hreintke
Do you you checked the proper operation spiffy compiled by You?

---

Spiffy compilation:

23:53:37 ***\* Build of configuration Default for project spiffy ****
mingw32-make.exe -f C:/tools/spiffy/Makefile all 
... depend build/spiffs_check.d
... depend build/spiffs_cache.d
... depend build/spiffs_hydrogen.d
... depend build/spiffs_gc.d
... depend build/spiffs_nucleus.d
... depend build/main.d
... compile build/main.o
... compile build/spiffs_nucleus.o
... compile build/spiffs_gc.o
... compile build/spiffs_hydrogen.o
... compile build/spiffs_cache.o
... compile build/spiffs_check.o
... linking

23:53:40 Build Finished (took 2s.990ms)

---

My program compilation:
..
..

# Generating spiffs_bin

Checking for spiffs files
files directory exists. Creating out/firmware/spiff_rom.bin
Creating rom spiff_rom.bin of size 128000 bytes
Adding files in directory files
index.html added to spiffs (12168 bytes)
settings.html added to spiffs (4096 bytes)
style.css added to spiffs (7329 bytes)
out/firmware/spiff_rom.bin---------->0x4C000

---

and ftp dir :

ww1
If I use spiffy.exe from  alonewolfx2   the files are then correct

(PS. I am using the last CHERTS Unofficial Development Kit for Espressif ESP8266 on windows 7,
all (sming and spiffy) are develop

**Comment by alonewolfx2** [comment]
what is your gcc version and msys version?compiling seems ok but 130kb is wrong. propably you dont have msys environment or wrong mingw. but it must be compile newer gcc with  @raburton's prç did you try lastest mingw?

**Comment by hreintke** [comment]
@flexiti : Another item : 
The "new spiffy", the one with the "fixed errno", only works correctly with a patch implemented in sming.
Both spiffy and sming have the update/new version implemented in their develop branch.
You should use both develop or both master

**Comment by flexiti** [comment]
@hreintke  
Yes,I did so (both develop).  I wrote about it- You answer before reading? :))))
 btw. What size have Yours spiffy.exe ?

@alonewolfx2 
mine mingw is no more than 4-5 months, ok, I check for a new one.
But I do not see why this simple program would have such requirements to the latest compiler - you not surprised?
You have closed the topic, it means that you do not want to write about it any more?

**Comment by hreintke** [comment]
@flexiti : 
Reading : sorry a little too quick. early morning here :)
Size : 
"Old spiffy" -> 779 KB (798.064 bytes)
"New spiffy" -> 171 KB (175.646 bytes)
Compiled with : `gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.2.0`
But.. I did not run/use new spiffy yet. Will do later today.

PS Not 100% but almost sure in the following.
The "Old spiffy" was dependent on an "Old gcc version", the "New spiffy" should be version independent

**Comment by flexiti** [comment]
@hreintke  ok,  the same size as mine,thanks, check please  and let me know   :)  Thanks :))

**Comment by raburton** [comment]
Your file size is fine, mine is only 160,425 bytes.

```
D:\Projects\esp8266-priv\spiffy>gcc --version
gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

D:\Projects\esp8266-priv\spiffy>make
... depend build/spiffs_check.d
... depend build/spiffs_cache.d
... depend build/spiffs_hydrogen.d
... depend build/spiffs_gc.d
... depend build/spiffs_nucleus.d
... depend build/main.d
... compile build/main.o
... compile build/spiffs_nucleus.o
... compile build/spiffs_gc.o
... compile build/spiffs_hydrogen.o
... compile build/spiffs_cache.o
... compile build/spiffs_check.o
... linking

D:\Projects\esp8266-priv\spiffy>cd build

D:\Projects\esp8266-priv\spiffy\build>.\spiffy.exe
Usage: .\spiffy.exe maxFsSizeinByte spiffsBaseDir
There is no specific size or files directory.
Starting in compatibility mode.
Default fs size is 196608 and directory is files.
Creating rom spiff_rom.bin of size 196608 bytes
Adding files in directory files
empty.txt added to spiffs (5 bytes)

D:\Projects\esp8266-priv\spiffy\build>dir
 Volume in drive D is Data
 Volume Serial Number is BEE8-2C65

 Directory of D:\Projects\esp8266-priv\spiffy\build

09/10/2015  08:12 AM    <DIR>          .
09/10/2015  08:12 AM    <DIR>          ..
29/09/2015  09:26 PM    <DIR>          files
09/10/2015  08:11 AM             3,185 main.d
09/10/2015  08:11 AM             9,889 main.o
09/10/2015  08:11 AM             3,006 spiffs_cache.d
09/10/2015  08:11 AM             9,843 spiffs_cache.o
09/10/2015  08:11 AM             3,006 spiffs_check.d
09/10/2015  08:11 AM            23,743 spiffs_check.o
09/10/2015  08:11 AM             2,997 spiffs_gc.d
09/10/2015  08:11 AM            15,704 spiffs_gc.o
09/10/2015  08:11 AM             3,015 spiffs_hydrogen.d
09/10/2015  08:11 AM            21,523 spiffs_hydrogen.o
09/10/2015  08:11 AM             3,012 spiffs_nucleus.d
09/10/2015  08:11 AM            42,223 spiffs_nucleus.o
09/10/2015  08:11 AM           160,425 spiffy.exe
09/10/2015  08:12 AM           196,608 spiff_rom.bin
              14 File(s)        498,179 bytes
               3 Dir(s)  1,131,085,185,024 bytes free

D:\Projects\esp8266-priv\spiffy\build>
```

Flashed to device, test file present and contents as expected.

**Comment by flexiti** [comment]
@raburton 
Thanks for info :) 
Did You check file via ftp ? there are good ? (please add 2-3 for test)

**Comment by raburton** [comment]
Tested with 3 files, fine. Not tested with ftp, spiffs is working so it should work with any access method, if it doesn't work with ftp then the issues isn't likely to be with spiffs.

**Comment by flexiti** [comment]
@raburton 
if I change spiffy.exe for old one (800kb exe file form alonewolfx2  - than files are ok in ftp.)

**Comment by flexiti** [comment]
I will change gcc to newest and check

**Comment by raburton** [comment]
If you change to old spiffy (not built from spiffy development branch) the spiffs should be incompatible with the development branch of sming. If you find the old version works then it sounds like you don't have the fix applied to sming.

**Comment by alonewolfx2** [comment]
@flexiti no ofcourse you can write. But I closed this pr. It's wrong place for this subject. Please open new issue and we will continue. I will do more test about this issue.

**Comment by flexiti** [comment]
Thanks for clue @raburton 
It's good now , that's all in this issue.
Yesterday I was downloaded Sming develop and wrote that develop not contain path #307 yet.  (spiffs fix)
After that, within the day, this patch was merged to develop.
 I added myself these path manually to my develop copy  ... but not compiled SmingFramework,I compiled only  my program :) sorry @hreintke @raburton @alonewolfx2  and thanks for time :))

btw. I am not familiar with linux, more with windows.
So I was installed compiler acording CHERTS  (it is gcc (GCC) 3.4.4 (msys special)) 
Spiffy compilation is ok ad have aprox 170 kb.
You guys have a different compiler

**Comment by alonewolfx2** [comment]
@flexiti is it working now ?

**Comment by flexiti** [comment]
@alonewolfx2 Yes,  its ok now, clue was last spiffs fix.  Thanks

**Pull request closed without merging**
